pasapi: api.sys.pcflab.jp
pksapi: api.pks.pcflab.jp:8443
grafana: grafana.pcflab.jp:3000
hw: healthwatch.sys.pcflab.jp
harbor: harbor.pcflab.jp
opsman: opsmanager.pcflab.jp
metrics: metrics.sys.pcflab.jp
redis: redis-broker.sys.pcflab.jp 